"""Public surfaces for the executable v1 DSL and candidate-only v2 DSL."""

from .canonical import canonical_hash, canonical_json
from .models import (
    AllCondition,
    AnyCondition,
    BacktestConfig,
    CatalogRef,
    DailyExecutionPolicy,
    EventCondition,
    EventDocumentTextPredicate,
    FirstOfExit,
    HoldingPeriodExit,
    IndicatorCondition,
    Instrument,
    NotCondition,
    PositionReturnExit,
    StrategySpec,
    TrailingDrawdownExit,
    iter_event_conditions,
    iter_financial_conditions,
    iter_holding_period_exits,
    iter_indicator_conditions,
    iter_position_return_exits,
    iter_trailing_drawdown_exits,
    strategy_requires_events,
    strategy_requires_financials,
)
from .models import (
    FinancialCondition as FinancialConditionV1,
)
from .models_v2 import (
    AllConditionV2,
    AnyConditionV2,
    BacktestConfigV2,
    CatalogRefV2,
    ConditionGrounding,
    EventAttributePredicate,
    EventConditionV2,
    FinancialCondition,
    InterpretationCoverage,
    NotConditionV2,
    SourceSpan,
    StrategySpecV2,
    TechnicalConditionV2,
    canonical_hash_v2,
    canonical_json_v2,
    iter_condition_leaf_paths,
)
from .validation import StrategyCatalogError, validate_strategy_against_catalog
from .validation_v2 import (
    ConditionGroundingExpectation,
    DatasetCoverageV2,
    ExecutableStrategyPlan,
    StrategyCandidateV2,
    StrategyV2ValidationContext,
    StrategyV2ValidationError,
    ValidationStage,
    validate_strategy_candidate_v2,
)

__all__ = [
    "AllCondition",
    "AllConditionV2",
    "AnyCondition",
    "AnyConditionV2",
    "BacktestConfig",
    "BacktestConfigV2",
    "CatalogRef",
    "CatalogRefV2",
    "ConditionGrounding",
    "ConditionGroundingExpectation",
    "DailyExecutionPolicy",
    "DatasetCoverageV2",
    "EventAttributePredicate",
    "EventCondition",
    "EventConditionV2",
    "EventDocumentTextPredicate",
    "ExecutableStrategyPlan",
    "FinancialCondition",
    "FinancialConditionV1",
    "FirstOfExit",
    "HoldingPeriodExit",
    "IndicatorCondition",
    "Instrument",
    "InterpretationCoverage",
    "NotCondition",
    "NotConditionV2",
    "PositionReturnExit",
    "SourceSpan",
    "StrategyCandidateV2",
    "StrategyCatalogError",
    "StrategySpec",
    "StrategySpecV2",
    "StrategyV2ValidationContext",
    "StrategyV2ValidationError",
    "TechnicalConditionV2",
    "TrailingDrawdownExit",
    "ValidationStage",
    "canonical_hash",
    "canonical_hash_v2",
    "canonical_json",
    "canonical_json_v2",
    "iter_condition_leaf_paths",
    "iter_event_conditions",
    "iter_financial_conditions",
    "iter_holding_period_exits",
    "iter_indicator_conditions",
    "iter_position_return_exits",
    "iter_trailing_drawdown_exits",
    "strategy_requires_events",
    "strategy_requires_financials",
    "validate_strategy_against_catalog",
    "validate_strategy_candidate_v2",
]
