"""Strategy DSL v1 public surface."""

from .canonical import canonical_hash, canonical_json
from .models import (
    AllCondition,
    AnyCondition,
    BacktestConfig,
    CatalogRef,
    DailyExecutionPolicy,
    EventCondition,
    EventDocumentTextPredicate,
    FirstOfExit,
    HoldingPeriodExit,
    IndicatorCondition,
    Instrument,
    NotCondition,
    PositionReturnExit,
    StrategySpec,
    TrailingDrawdownExit,
    iter_event_conditions,
    iter_holding_period_exits,
    iter_indicator_conditions,
    iter_position_return_exits,
    iter_trailing_drawdown_exits,
    strategy_requires_events,
)
from .validation import StrategyCatalogError, validate_strategy_against_catalog

__all__ = [
    "AllCondition",
    "AnyCondition",
    "BacktestConfig",
    "CatalogRef",
    "DailyExecutionPolicy",
    "EventCondition",
    "EventDocumentTextPredicate",
    "FirstOfExit",
    "HoldingPeriodExit",
    "IndicatorCondition",
    "Instrument",
    "NotCondition",
    "PositionReturnExit",
    "StrategyCatalogError",
    "StrategySpec",
    "TrailingDrawdownExit",
    "canonical_hash",
    "canonical_json",
    "iter_event_conditions",
    "iter_holding_period_exits",
    "iter_indicator_conditions",
    "iter_position_return_exits",
    "iter_trailing_drawdown_exits",
    "strategy_requires_events",
    "validate_strategy_against_catalog",
]
