"""Dialogue migration safety on disposable SQLite databases only."""

from collections.abc import Iterator
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.exc import DatabaseError

from alembic import command
from ashare_lab.api.persistent_store import DIALOGUE_METADATA, SQLAlchemyDraftStore

ROOT = Path(__file__).parents[2]
HEAD = "20260906_0006"
PREVIOUS = "20260831_0005"
_ROWS = {
    "dialogue_drafts": {
        "draft_id": "00000000-0000-0000-0000-000000000001", "latest_revision": 1,
        "storage_version": 1, "turns_json": "[]",
    },
    "dialogue_draft_revisions": {
        "draft_id": "00000000-0000-0000-0000-000000000001", "revision": 1,
        "payload_json": '{"fixture":"original revision"}',
    },
    "dialogue_idempotency": {
        "scope": "create", "key": "fixture-request", "request_hash": "sha256:" + "a" * 64,
        "payload_json": '{"fixture":"original response"}',
    },
    "dialogue_backtest_reviews": {
        "run_id": "run:fixture", "response_hash": "sha256:" + "b" * 64,
        "payload_json": '{"fixture":"original review"}',
    },
}


@pytest.fixture
def database(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> Iterator[tuple[Config, sa.Engine]]:
    url = f"sqlite+pysqlite:///{tmp_path / 'dialogue-migration.db'}"
    monkeypatch.setenv("DATABASE_URL", url)
    config = Config(str(ROOT / "alembic.ini"))
    command.upgrade(config, PREVIOUS)
    engine = sa.create_engine(url)
    try:
        yield config, engine
    finally:
        engine.dispose()


def _seed(engine: sa.Engine, names: set[str]) -> None:
    with engine.begin() as connection:
        for name in names:
            connection.execute(DIALOGUE_METADATA.tables[name].insert().values(**_ROWS[name]))


def _snapshot(engine: sa.Engine) -> dict[str, list[dict[str, object]]]:
    names = set(sa.inspect(engine).get_table_names()) & set(DIALOGUE_METADATA.tables)
    with engine.connect() as connection:
        return {
            name: [dict(row) for row in connection.execute(
                sa.select(DIALOGUE_METADATA.tables[name]),
            ).mappings()]
            for name in names
        }


def _revision(engine: sa.Engine) -> str | None:
    with engine.connect() as connection:
        return MigrationContext.configure(connection).get_current_revision()


@pytest.mark.parametrize("partial", [False, True])
def test_adopts_create_all_tables_and_preserves_every_existing_row(
    database: tuple[Config, sa.Engine], partial: bool, monkeypatch: pytest.MonkeyPatch,
) -> None:
    config, engine = database
    tables = (
        [DIALOGUE_METADATA.tables["dialogue_drafts"]] if partial
        else list(DIALOGUE_METADATA.sorted_tables)
    )
    DIALOGUE_METADATA.create_all(engine, tables=tables)
    _seed(engine, {table.name for table in tables})
    before = _snapshot(engine)

    command.upgrade(config, "head")
    command.check(config)
    after = _snapshot(engine)
    assert set(after) == set(DIALOGUE_METADATA.tables)
    assert all(after[name] == rows for name, rows in before.items())
    assert all(after[name] == [] for name in set(after) - set(before))
    assert _revision(engine) == HEAD

    def disallow_create_all(*args: object, **kwargs: object) -> None:
        raise AssertionError("production initialization must not create schema")

    monkeypatch.setattr(DIALOGUE_METADATA, "create_all", disallow_create_all)
    SQLAlchemyDraftStore(engine, initialize_schema=False)
    command.upgrade(config, "head")
    assert _snapshot(engine) == after


@pytest.mark.parametrize("defect", [
    "missing_column", "wrong_type", "unbounded_string", "untyped_column", "wrong_pk",
    "extra_default", "extra_constraint", "view",
])
def test_incompatible_existing_object_fails_before_creating_missing_tables(
    database: tuple[Config, sa.Engine], defect: str,
) -> None:
    config, engine = database
    if defect == "view":
        with engine.begin() as connection:
            connection.exec_driver_sql("CREATE VIEW dialogue_drafts AS SELECT 1 AS storage_version")
    elif defect == "untyped_column":
        with engine.begin() as connection:
            connection.exec_driver_sql(
                "CREATE TABLE dialogue_drafts (draft_id VARCHAR(36) NOT NULL PRIMARY KEY, "
                "latest_revision INTEGER NOT NULL, storage_version INTEGER NOT NULL, "
                "turns_json NOT NULL)"
            )
    else:
        length = None if defect == "unbounded_string" else 35 if defect == "wrong_type" else 36
        columns: list[sa.SchemaItem] = [
            sa.Column("draft_id", sa.String(length), primary_key=True),
            sa.Column("latest_revision", sa.Integer(), nullable=False,
                      primary_key=defect == "wrong_pk"),
            sa.Column("storage_version", sa.Integer(), nullable=False,
                      server_default=sa.text("1") if defect == "extra_default" else None),
        ]
        if defect != "missing_column":
            columns.append(sa.Column("turns_json", sa.Text(), nullable=False))
        if defect == "extra_constraint":
            columns.append(sa.CheckConstraint("storage_version > 0"))
        sa.Table("dialogue_drafts", sa.MetaData(), *columns).create(engine)
    before_tables = set(sa.inspect(engine).get_table_names())
    with pytest.raises(RuntimeError, match="dialogue schema"):
        command.upgrade(config, "head")
    assert set(sa.inspect(engine).get_table_names()) == before_tables
    assert _revision(engine) == PREVIOUS


def test_dialogue_metadata_is_in_the_alembic_drift_gate(database: tuple[Config, sa.Engine]) -> None:
    config, engine = database
    command.upgrade(config, "head")
    with engine.begin() as connection:
        connection.exec_driver_sql("ALTER TABLE dialogue_drafts ADD COLUMN unexpected TEXT")
    with pytest.raises(AutogenerateDiffsDetected, match="unexpected"):
        command.check(config)


def test_downgrade_refuses_before_deleting_history_or_changing_revision(
    database: tuple[Config, sa.Engine],
) -> None:
    config, engine = database
    command.upgrade(config, "head")
    _seed(engine, set(DIALOGUE_METADATA.tables))
    before = _snapshot(engine)
    with pytest.raises(RuntimeError, match="downgrade is disabled to preserve history"):
        command.downgrade(config, PREVIOUS)
    assert _snapshot(engine) == before and _revision(engine) == HEAD


def test_append_only_guards_preserve_history_and_allow_draft_head_updates(
    database: tuple[Config, sa.Engine],
) -> None:
    config, engine = database
    command.upgrade(config, "head")
    _seed(engine, set(DIALOGUE_METADATA.tables))
    before = _snapshot(engine)
    for name in set(DIALOGUE_METADATA.tables) - {"dialogue_drafts"}:
        table = DIALOGUE_METADATA.tables[name]
        for statement in (table.update().values(payload_json="{}"), table.delete()):
            with pytest.raises(DatabaseError, match="append-only"), engine.begin() as connection:
                connection.execute(statement)
    assert _snapshot(engine) == before
    head = DIALOGUE_METADATA.tables["dialogue_drafts"]
    with engine.begin() as connection:
        result = connection.execute(head.update().where(head.c.storage_version == 1).values(
            storage_version=2,
        ).returning(head.c.storage_version))
        assert result.scalar_one() == 2


def test_postgresql_guard_names_match_the_append_only_acl_contract(
    database: tuple[Config, sa.Engine],
) -> None:
    config, _ = database
    revision = ScriptDirectory.from_config(config).get_revision(HEAD)
    assert revision is not None
    ddl = revision.module._immutability_ddl("postgresql")
    triggers = [statement for statement in ddl if statement.startswith("CREATE TRIGGER")]
    assert len(triggers) == 3
    for name in set(DIALOGUE_METADATA.tables) - {"dialogue_drafts"}:
        assert any(f"CREATE TRIGGER trg_{name}_immutable BEFORE UPDATE OR DELETE ON {name}"
                   in statement for statement in triggers)
    assert not any("ON dialogue_drafts" in statement for statement in triggers)
