import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, vi } from 'vitest'
import App from './App'
import { backtestApi, instrumentApi, strategyApi } from './shared/api/client'
import * as gallerySamples from './shared/strategy-gallery-samples'
import sampleData from '../public/strategy-gallery-samples.json'
import { recentBacktestsKey } from './shared/recent-backtests'

const stock = { symbol: '600519.SH', name: '贵州茅台', market: 'CN_A' as const, exchange: 'SSE' as const }
const renderApp = () => render(<QueryClientProvider client={new QueryClient({ defaultOptions: {
  queries: { retry: false }, mutations: { retry: false },
} })}><App /></QueryClientProvider>)
beforeEach(() => {
  vi.spyOn(gallerySamples, 'fetchGallerySamples').mockResolvedValue([])
  vi.spyOn(strategyApi, 'compile').mockResolvedValue({ status: 'needs_clarification',
    draftId: 'gallery-new-draft', revision: 1, assistantMessage: '请审阅生成的策略。',
    clarification: { id: 'idea_guidance_required', question: '请审阅生成的策略。', reason: '', choices: [] } })
})
afterEach(() => { vi.restoreAllMocks(); window.history.replaceState(null, '', '/') })

it('opens the same sample report and returns without creating a run or overwriting the conversation', async () => {
  vi.mocked(gallerySamples.fetchGallerySamples).mockResolvedValue(gallerySamples.decodeGallerySamples(sampleData))
  const compile = vi.spyOn(strategyApi, 'compile')
  const create = vi.spyOn(backtestApi, 'create')
  const review = vi.spyOn(backtestApi, 'review')
  const user = userEvent.setup()
  renderApp()
  const text = '保留这条尚未发送的策略'
  fireEvent.change(screen.getByLabelText('交易规则'), { target: { value: text } })
  const historyBefore = localStorage.getItem(recentBacktestsKey('mock'))
  await user.click(screen.getByRole('button', { name: '策略广场' }))
  await user.click(await screen.findByRole('button', { name: '查看均线跟随回测' }))
  expect(screen.getByText('样例回测 · 只读')).toBeVisible()
  expect(screen.getByRole('tab', { name: '回测报告' })).toHaveAttribute('aria-selected', 'true')
  expect(screen.queryByRole('button', { name: '编辑策略' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: '返回策略广场' }))
  expect(await screen.findByRole('button', { name: '查看均线跟随回测' })).toBeVisible()
  await user.click(screen.getByRole('button', { name: `${text}，当前` }))
  expect(screen.getByLabelText('交易规则')).toHaveValue(text)
  expect(localStorage.getItem(recentBacktestsKey('mock'))).toBe(historyBefore)
  expect(compile).not.toHaveBeenCalled()
  expect(create).not.toHaveBeenCalled()
  expect(review).not.toHaveBeenCalled()
})

it('preserves the daily observation of price-plan samples', async () => {
  vi.mocked(gallerySamples.fetchGallerySamples).mockResolvedValue(gallerySamples.decodeGallerySamples(sampleData))
  vi.spyOn(instrumentApi, 'search').mockResolvedValue({ items: [stock], hasMore: false })
  window.history.replaceState(null, '', '/#strategies')
  const user = userEvent.setup()
  renderApp()
  await screen.findByRole('button', { name: '查看先买后卖回测' })
  expect(screen.queryByRole('button', { name: '使用高位回落保护策略' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: '使用先买后卖策略' }))
  await user.type(screen.getByLabelText('回测标的'), '600519')
  await user.click(await screen.findByRole('button', { name: /贵州茅台.*600519.SH/ }, { timeout: 3_000 }))
  await screen.findByText('已选：贵州茅台 600519.SH')
  await user.click(screen.getByRole('button', { name: '生成策略' }))
  expect(vi.mocked(strategyApi.compile).mock.calls[0]?.[0].utterance).toContain('按日线收盘观察价格条件')
})

it('keeps the current conversation and typed input across gallery, filters and browser navigation', async () => {
  const user = userEvent.setup()
  const compile = vi.spyOn(strategyApi, 'compile')
  renderApp()
  const text = '这条当前输入要保留'
  fireEvent.change(screen.getByLabelText('交易规则'), { target: { value: text } })
  await user.click(screen.getByRole('button', { name: '策略广场' }))
  expect(window.location.hash).toBe('#strategies')
  expect(screen.getByRole('heading', { name: '精选策略' })).toBeVisible()
  expect(screen.getAllByRole('button', { name: /^查看.+策略$/ })).toHaveLength(10)
  expect(screen.queryByRole('button', { name: '持仓保护' })).not.toBeInTheDocument()
  const current = screen.getByRole('button', { name: `${text}，当前` })
  expect(current).toBeVisible()
  expect(current).not.toHaveClass('is-active')
  await user.type(screen.getByRole('searchbox'), '没有这个策略')
  expect(screen.getByText('暂时没有匹配的策略')).toBeVisible()
  await user.click(current)
  expect(screen.getByLabelText('交易规则')).toHaveValue(text)
  await user.click(screen.getByRole('button', { name: '策略广场' }))
  expect(screen.getByRole('searchbox')).toHaveValue('没有这个策略')
  await user.click(screen.getByRole('button', { name: '查看全部策略' }))
  act(() => { window.history.replaceState(null, '', '/'); window.dispatchEvent(new PopStateEvent('popstate')) })
  expect(screen.getByLabelText('交易规则')).toHaveValue(text)
  expect(document.querySelector('#pg-chat')).toHaveAttribute('data-view', 'chat')
  act(() => { window.history.replaceState(null, '', '/#strategies'); window.dispatchEvent(new PopStateEvent('popstate')) })
  expect(screen.getByRole('heading', { name: '精选策略' })).toBeVisible()
  expect(compile).not.toHaveBeenCalled()
})

it('opens a gallery deep link and generates once after stock confirmation without starting a backtest', async () => {
  window.history.replaceState(null, '', '/#strategies')
  const user = userEvent.setup()
  const search = vi.spyOn(instrumentApi, 'search').mockResolvedValue({ items: [stock], hasMore: false })
  const compile = vi.spyOn(strategyApi, 'compile').mockImplementation(() => new Promise(() => {}))
  const create = vi.spyOn(backtestApi, 'create')
  renderApp()
  await user.click(screen.getByRole('button', { name: '查看均线跟随策略' }))
  await user.click(screen.getByRole('button', { name: '用这个策略' }))
  await user.type(screen.getByLabelText('回测标的'), '贵州茅台')
  expect(screen.queryByRole('button', { name: '查找股票' })).not.toBeInTheDocument()
  const option = await screen.findByRole('button', { name: /贵州茅台.*600519.SH/ })
  expect(screen.queryByText('已选：贵州茅台 600519.SH')).not.toBeInTheDocument()
  await user.click(option)
  expect(search).toHaveBeenCalledWith('贵州茅台', expect.any(AbortSignal))
  expect(await screen.findByText('已选：贵州茅台 600519.SH')).toBeVisible()
  await user.click(screen.getByRole('button', { name: '生成策略' }))
  expect(screen.getByLabelText('交易规则')).toHaveValue('')
  expect(compile.mock.calls[0]?.[0].utterance).toBe('贵州茅台（600519.SH），均线跟随。买入规则：5日均线上穿20日均线；卖出规则：5日均线下穿20日均线。')
  expect(window.location.hash).toBe('')
  expect(create).not.toHaveBeenCalled()
  await waitFor(() => expect(compile).toHaveBeenCalledTimes(1))
  expect(compile.mock.calls[0]?.[0]).toEqual(expect.objectContaining({ instrument: stock,
    instrumentContextSource: 'stock_page', relatedRunIds: [], relatedReviews: [] }))
  expect(compile.mock.calls[0]?.[1]).toBeUndefined()
  expect(create).not.toHaveBeenCalled()
})

it.each(['sidebar', 'browser'])('returns to the gallery list after using a strategy via %s navigation', async navigation => {
  window.history.replaceState(null, '', '/#strategies')
  vi.spyOn(instrumentApi, 'search').mockResolvedValue({ items: [stock], hasMore: false })
  const compile = vi.spyOn(strategyApi, 'compile')
  const create = vi.spyOn(backtestApi, 'create')
  const user = userEvent.setup()
  renderApp()
  await user.click(screen.getByRole('button', { name: '查看均线跟随策略' }))
  await user.click(screen.getByRole('button', { name: '用这个策略' }))
  fireEvent.change(screen.getByLabelText('回测标的'), { target: { value: '茅台' } })
  const form = within(screen.getByLabelText('回测标的').closest('form')!)
  await user.click(await form.findByRole('button', { name: /贵州茅台.*600519.SH/ }, { timeout: 3000 }))
  await user.click(screen.getByRole('button', { name: '生成策略' }))
  await screen.findByText('请审阅生成的策略。')
  const text = (screen.getByLabelText('交易规则') as HTMLTextAreaElement).value
  if (navigation === 'sidebar') await user.click(screen.getByRole('button', { name: '策略广场' }))
  else act(() => { window.history.replaceState(null, '', '/#strategies'); window.dispatchEvent(new PopStateEvent('popstate')) })
  expect(screen.getByRole('heading', { name: '精选策略' })).toBeVisible()
  expect(screen.queryByRole('heading', { name: '选择回测股票' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: '查看均线跟随策略' }))
  await user.click(screen.getByRole('button', { name: '用这个策略' }))
  expect(screen.getByLabelText('回测标的')).toHaveValue('')
  // The primary navigation also returns to the list when already inside the library.
  await user.click(screen.getByRole('button', { name: '策略广场' }))
  expect(screen.getByRole('heading', { name: '精选策略' })).toBeVisible()
  act(() => { window.history.replaceState(null, '', '/'); window.dispatchEvent(new PopStateEvent('popstate')) })
  expect(screen.getByLabelText('交易规则')).toHaveValue(text)
  expect(compile).toHaveBeenCalledTimes(1)
  expect(create).not.toHaveBeenCalled()
}, 10_000)

it('retains failed suggestion input and retries without carrying over the previously selected stock', async () => {
  window.history.replaceState(null, '', '/#strategies')
  const replacement = { ...stock, name: '顶点软件', symbol: '603383.SH' }
  const search = vi.spyOn(instrumentApi, 'search')
    .mockResolvedValueOnce({ items: [stock], hasMore: false })
    .mockRejectedValueOnce(new Error('股票查询暂时不可用'))
    .mockResolvedValueOnce({ items: [replacement], hasMore: false })
  const compile = vi.spyOn(strategyApi, 'compile')
  const create = vi.spyOn(backtestApi, 'create')
  const user = userEvent.setup()
  renderApp()
  await user.click(screen.getByRole('button', { name: '查看均线跟随策略' }))
  await user.click(screen.getByRole('button', { name: '用这个策略' }))
  const input = screen.getByLabelText('回测标的')
  fireEvent.change(input, { target: { value: '茅台' } })
  await user.click(await screen.findByRole('button', { name: /贵州茅台.*600519.SH/ }))
  fireEvent.change(input, { target: { value: '顶' } })
  expect(screen.queryByText('已选：贵州茅台 600519.SH')).not.toBeInTheDocument()
  await screen.findByText('股票查询暂时不可用')
  expect(input).toHaveValue('顶')
  await user.click(screen.getByRole('button', { name: '重新匹配' }))
  await user.click(await screen.findByRole('button', { name: /顶点软件.*603383.SH/ }))
  expect(search).toHaveBeenCalledTimes(3)
  expect(search.mock.calls.map(call => call[0])).toEqual(['茅台', '顶', '顶'])
  await user.click(screen.getByRole('button', { name: '生成策略' }))
  expect(compile.mock.calls[0]?.[0].utterance).toContain('顶点软件（603383.SH）')
  expect(compile).toHaveBeenCalledTimes(1)
  expect(create).not.toHaveBeenCalled()
})

it('debounces composition and ignores stale suggestions after typing or clearing', async () => {
  window.history.replaceState(null, '', '/#strategies')
  let resolveOld!: (value: { items: typeof stock[]; hasMore: boolean }) => void
  const search = vi.spyOn(instrumentApi, 'search')
    .mockImplementationOnce(() => new Promise(resolve => { resolveOld = resolve }))
    .mockResolvedValue({ items: [stock], hasMore: false })
  const user = userEvent.setup()
  renderApp()
  await user.click(screen.getByRole('button', { name: '查看均线跟随策略' }))
  await user.click(screen.getByRole('button', { name: '用这个策略' }))
  const input = screen.getByLabelText('回测标的')
  fireEvent.compositionStart(input)
  fireEvent.change(input, { target: { value: '顶' } })
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 350)) })
  expect(search).not.toHaveBeenCalled()
  fireEvent.compositionEnd(input)
  await waitFor(() => expect(search).toHaveBeenCalledWith('顶', expect.any(AbortSignal)))
  fireEvent.change(input, { target: { value: '茅台' } })
  expect(search.mock.calls[0]?.[1]?.aborted).toBe(true)
  await screen.findByRole('button', { name: /贵州茅台.*600519.SH/ })
  await act(async () => { resolveOld({ items: [{ ...stock, name: '顶点软件', symbol: '603383.SH' }], hasMore: false }) })
  expect(screen.queryByRole('button', { name: /顶点软件/ })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: /贵州茅台.*600519.SH/ }))
  expect(screen.getByText('已选：贵州茅台 600519.SH')).toBeVisible()
  fireEvent.change(input, { target: { value: '' } })
  expect(screen.queryByText('已选：贵州茅台 600519.SH')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: /贵州茅台.*600519.SH/ })).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: '生成策略' })).toBeDisabled()
})
